### ISSUE TITLE
Is it possible to call struct method?

### ISSUE THREAD

**Issue by nhphu** [taiki-e/pin-project-lite#10]
```rust
use std::pin::Pin;
use pin_project_lite::pin_project;
pin_project! {
    struct Struct<T, U> {
        #[pin]
        pinned: T,
        unpinned: U,
    }
}

impl<T, U> Struct<T, U> {
    fn foo(self: Pin<&mut Self>) {
        let this = self.project();
        //
        this.bar();
    }

    fn bar(&self) {

    }
}
```
Compiler emit error:

> no method named `bar` found for type `_::Projection<'_, T, U>` in the current scope
> method not found in `_::Projection<'_, T, U>`

**Comment by taiki-e** [comment]
`.project()` returns a different type from `self`, so it needs to call `bar` from `self` directly:

```diff
  impl<T, U> Struct<T, U> {
-     fn foo(self: Pin<&mut Self>) {
-         let this = self.project();
+     fn foo(mut self: Pin<&mut Self>) {
+         let this = self.as_mut().project();
          //
-         this.bar();
+         self.bar();
      }
```

(and `project` consumes `self`, so reborrow the `Pin<&mut Self>` via [`as_mut`](https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#method.as_mut).)

**Comment by nhphu** [comment]
Thank you for your help
