### ISSUE TITLE
local ambiguity: multiple parsing options: built-in NTs tt ('generics') or 1 other option

### ISSUE THREAD

**Issue by fafhrd91** [taiki-e/pin-project-lite#31]
got error "local ambiguity: multiple parsing options: built-in NTs tt ('generics') or 1 other option" with version 0.1.8

code that fails looks like:

```rust

pin_project_lite::pin_project! {
#[doc(hidden)]
pub struct HttpServiceResponse<
    T,
    S: ServiceFactory,
    B,
    X: ServiceFactory,
    U: ServiceFactory,
> {
...
}}
```

**Comment by taiki-e** [comment]
Published 0.1.9 which fixes this issue, thanks @fafhrd91 for the reporting!
