### ISSUE TITLE
`no such field` in `new` function

### ISSUE THREAD

**Issue by FH0** [taiki-e/pin-project-lite#81]
```rust
pin_project! {
    struct Test<T> {
        value: T,
    }
}

impl<T: Unpin> Test<T> {
    pub fn new(value: T) -> Self {
        Self { value }
    }
}
```

![image](https://github.com/taiki-e/pin-project-lite/assets/32861476/60957063-4aab-48fd-8ad3-acc1adf85acd)

I am a novice learning Rust. Compiler is unhappy after I added `pin_project!` to `Test`.

**Comment by taiki-e** [comment]
This rust-analyzer bug. Compilation passes without problems. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fd79e5cda66a9d465cb050c889af5bb1
